[tool.poetry]
name = "mock-alchemy"
version = "0.1.0"
description = "SQLAlchemy mock helpers."
license = "MIT"
homepage = "https://github.com/rajivsarvepalli/mock-alchemy"
repository = "https://github.com/rajivsarvepalli/mock-alchemy"
authors = ["Rajiv Sarvepalli <rajiv@sarvepalli.net>", "Miroslav Shubernetskiy <mail@miki725.com>", "Serkan Hoscai <serkan@hosca.com"]
readme = "README.rst"
keywords = ["sqlalchemy mock testing", "sqlalchemy mock", "mock sqlalchemy"]
documentation = "https://mockalchemy.readthedocs.io"
classifiers=[
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Development Status :: 2 - Pre-Alpha",
]

[tool.poetry.dependencies]
python = ">=2.7, >=3.6.1 <4"
SQLAlchemy = "^1.3.22"
six = "^1.15.0"


[tool.poetry.dev-dependencies]
black = { version = "^20.8b1", python = "^3.6" }
flake8-bugbear = { version = "^20.0", python = "^3.6" }
"collective.checkdocs" = "^0.2"
importanize = "^0.7.0"
mock = "^4.0.3"
pdbpp = "^0.10.2"
coverage = {extras = ["toml"], version = "^5.3.1", python = "^3.6"}
flake8 = "^3.8.4"
ptpython = "^3.0.9"
pytest = "^6.2.1"
pytest-cov = "^2.10.1"
tox = "^3.21.0"
pre-commit = { version = "^2.9", python = "^3.6" }
pre-commit-hooks = { version = "^3.0", python = "^3.6" }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
