name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
        pip install poetry==1.1.4
        pip install coverage[toml]
        pip install codecov
    - name: Test with tox
      run: tox
    - run: coverage xml --fail-under=0
    - run: codecov
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
