name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: x64
    - run: pip install tox
    - run: pip install poetry==1.1.4
    - run: pip install coverage[toml]
    - run: pip install codecov
    - run: tox
    - run: coverage xml --fail-under=0
    - run: codecov
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
